runtime: nodejs20
instance_class: F2
env_variables:
  DATABASE_URL: mysql://<USERNAME>:<PASSWORD>@/<DB_NAME>?socketPath=/cloudsql/<INSTANCE_CONNECTION_NAME>
  NODE_ENV: production
  JWT_SECRET: <YOUR_SECRET>
  PORT: 8080
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3
handlers:
  - url: /.*
    script: auto
